branch-defaults:
  task-9:
    environment: memos77-cart-api-prod
    group_suffix: null
global:
  application_name: memos77-cart-api
  branch: null
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
